# Generated by Django 4.1 on 2022-09-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_disc',
            new_name='item_desc',
        ),
    ]
